### PR TITLE
0.75.1 release update

### PR DESCRIPTION
**Pull request by dreamer**
I need to put some additional polish, but it's good enough for feedback IMHO :)

### CODE REVIEW

**Comment by kcgen** [comment]
Looks great @dreamer !
I pushed a couple commits (first is just a linter cleanup), second has wording suggestions.

**Review by kcgen — APPROVED** [review]
I haven't tested the links, but besides that looks good!

**Comment by dreamer** [comment]
Only few remaining TODOs to fill and I guess we're good to go. I reminded myself of one more bugfix we might consider backporting.

**Comment by dreamer** [comment]
@kcgen I made some final edits, overall I think we're ready for the relase.

There's one tiny thing to discuss: AUTHORS file. I've noticed packagers using AUTHORS file to fill metadata in their packages… which is annoying from our POV, I think we need to adjust it to reflect the project status.

I think I'm going to edit the file this way:
```
The dosbox-staging team:

Patryk Obara
kcgen

This project is a continuation of DOSBox, authored by:

<list of all members of DOSBox team>
```
Do you want me to use `kcgen`, `krc`, or your name and surname? Is this format ok or maybe I should change it somehow?

Do you think we should include Ant and Wengier? We gave them push access to the repo, but their contributions are rather small for now (I will probably add them to THANKS file instead).

**Review by kcgen — APPROVED** [review]

**Comment by kcgen** [comment]
Sorry for the late reply; not sure why this didn't appear in my github notification list? Maybe I didn't see it. Yes - what you've done looks good to me, thanks @dreamer.

**Pull request merged**
