### PR TITLE
Add a couple updates for 0.79

### PR DESCRIPTION
**Pull request by kcgen**
- Missing credit for Jon Campbell -- thank you @Wengier !
- Missing maintainer-specific thanks, including adding @shermp to the list
- Missing news for repository packagers
- Add @Wengier to maintainers, as this was the understanding during the 0.79 period

### CODE REVIEW

**Comment by Wengier** [comment]
As a DOSBox Staging maintainer, I highly appreciate your further updates to the release notes. Thanks @kcgen.

**Comment by kcgen** [comment]
@Wengier ,

I agree we should stick to the understanding that was present during the 0.79 period - and that understanding was that you were a maintainer, so I've added that as a commit.

I plan to document the distinction for the 0.80 so we all can choose or focus (if any of us have a preference), and more importantly, so there are no surprises.

(explanation in commit: <https://github.com/dosbox-staging/dosbox-staging.github.io/pull/16/commits/eca29373d4d44da8a2ffac6713f55ff7b2c10f71>)

**Review by johnnovak — APPROVED** [review]
👍🏻

**Comment by Wengier** [comment]
Thanks @kcgen. Merging.

**Pull request merged**
