### PR TITLE
Add MP4 encodings of the Wizball and Joycheck videos

### PR DESCRIPTION
**Pull request by kcgen**

### CODE REVIEW

**Comment by Wengier** [comment]
@kcgen Thanks for the additions. Perhaps the MP4 files should be attached as well?

**Comment by kcgen** [comment]
thanks for catching that :sweat_smile:! (attached now)

**Comment by Wengier** [comment]
Thanks. The MP4 video look great to me.

Not really a user-visible issue, but it appears that they do not use exactly the same file names as the WEBM counterpart. e.g.:
WEBM: pcspeaker_impulse_wizball.webm
MP4: pcspeaker_impulse_wizball-h264_aac.mp4

The previously added MP4 video for `Alone in the Dark` had the same file name as the WEBM counterpart:

WEBM: alone-in-the-dark-intro.webm
MP4: alone-in-the-dark-intro.mp4

**Comment by kcgen** [comment]
Good catch - renamed.

**Review by Wengier — APPROVED** [review]
Thanks for the additions and the fix! Merging.

**Pull request merged**
